// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/main-bower-files/main-bower-files.d.ts
declare module "main-bower-files" {

    interface IPaths {
        bowerDirectory?: string;
        bowerrc?: string;
        bowerJson?: string;
    }

    interface IFilterFunction {
        (filepath: string): boolean;
    }

    interface IOptions {
        debugging?: boolean;
        main?: string | string[] | Object;
        env?: string;
        paths?: IPaths | string;
        checkExistence?: boolean;
        includeDev?: boolean | string;
        includeSelf?: boolean;
        filter?: RegExp | IFilterFunction | string | string[];
    }

    function mainBowerFiles(options?: IOptions): string[];

    export = mainBowerFiles;
}
