// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/e3d395a870cdf8b7939a06c20622e5112a299080/gulp-strip-debug/gulp-strip-debug.d.ts
declare module "gulp-strip-debug" {
  const gulpStripDebug : () => NodeJS.ReadWriteStream;
  export = gulpStripDebug;
}
